name: Publish to NPM

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish (e.g., 1.0.0)'
        required: true
        type: string

jobs:
  publish-npm:
    name: Publish to NPM Registry
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1

      - name: Setup Node.js
        uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4.3.0
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Build package
        run: npm run build

      - name: Update version (if manual)
        if: github.event_name == 'workflow_dispatch'
        run: npm version ${{ inputs.version }} --no-git-tag-version

      - name: Publish to NPM
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create GitHub Release
        if: github.event_name == 'workflow_dispatch'
        uses: actions/create-release@fca5fb59dbfa2749e2850463e8c5af9e3ee0e270 # v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ inputs.version }}
          release_name: Release v${{ inputs.version }}
          body: |
            Release of n8n-nodes-brainsait v${{ inputs.version }}

            ## Changes
            See CHANGELOG.md for details

            ## Installation
            ```bash
            npm install n8n-nodes-brainsait@${{ inputs.version }}
            ```

          draft: false
          prerelease: false

  publish-github:
    name: Publish to GitHub Packages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1

      - name: Setup Node.js
        uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4.3.0
        with:
          node-version: '18'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@fadil369'

      - name: Install dependencies
        run: npm ci

      - name: Build package
        run: npm run build

      - name: Publish to GitHub Packages
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  notify-success:
    name: Notification - Success
    runs-on: ubuntu-latest
    needs: [publish-npm, publish-github]
    if: success()

    steps:
      - name: Success message
        run: |
          echo "✅ Package published successfully!"
          echo "📦 NPM: https://www.npmjs.com/package/n8n-nodes-brainsait"
          echo "🐙 GitHub: https://github.com/Fadil369/n8n-nodes-brainsait"
